export const MERCHANTS_QR_BUCKET = 'merchant-qr-codes';
export const NOTIFICATION_QUEUE = "NOTIFICATION_QUEUE";
export const MERCHANT_REGISTRATION_QUEUE = "MERCHANT_REGISTRATION_QUEUE"
export type QueueType = "NOTIFICATION_QUEUE" | "MERCHANT_REGISTRATION_QUEUE";

