import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/header'
import Providers from '@/providers'
//import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='mx-10'>
          <Header title="DURO" />
          <Providers>
            <div className='w-full flex'>
              {children}
            </div>
          </Providers>
        </div>
      </body>
    </html>
  )
}
